### PR TITLE
Added support for external providers as npm modules.

### PR DESCRIPTION
**Pull request by vergara**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by vergara** [comment]
I had to create a new pull request. I will close the old one.

**Comment by vergara** [comment]
@raymondfeng

**Comment by nickcmaynard** [comment]
+1

**Comment by loic-ps** [comment]
@vergara Is there any news about this pull request ?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Pull request merged**
