### PR TITLE
sub folder's file download

### PR DESCRIPTION
**Pull request by andrei0807**
#### Related issues

- connect to <link_to_referenced_issue>

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@strongloop/sq-lb-apex @hacksparrow , please review this one instead. thanks!

**Comment by hacksparrow** [comment]
@andrei0807 thanks for the PR. Can you add the corresponding test, please?

**Comment by andrei0807** [comment]
@hacksparrow 
What should I do?

**Comment by hacksparrow** [comment]
Take a look at the test files at https://github.com/strongloop/loopback-component-storage/tree/master/test to get an idea about what they are and how they work.

Your test case should test the feature you have implemented.

**Comment by hacksparrow** [comment]
@andrei0807 ^

**Pull request closed without merging**
