### PR TITLE
Bugfix: Cannot read property 'forEach' of undefined.

### PR DESCRIPTION
**Pull request by dgazcon27**
#### Related issues

- connect to <link_to_referenced_issue>

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by virkt25** [comment]
ok to test

**Comment by virkt25** [comment]
Hi @dgazcon27 can you rebase your PR on top of the latest master which should help fix the CI errors and then we can get this landed. If you need help with rebasing, please let me know. Thanks.

**Comment by dhmlau** [comment]
superseded by PR #279

**Pull request closed without merging**
