### PR TITLE
Refactor download

### PR DESCRIPTION
**Pull request by bajtos**
- Clean up "download()" implementation
- Continue middleware chain after download error

Supersedes #156

@Amir-61 or @loay please review
cc @raymondfeng

### CODE REVIEW

**Comment by loay** [comment]
LGTM

**Comment by Amir-61** [comment]
There was just a small nitpick for extra blank line and I preferred to fix it instead of commenting here. LGTM :shipit:

**Comment by bajtos** [comment]
Thanks.

I have published `loopback-component-storage@1.10.0` with the change.

@cadesalaberry enjoy :)

**Comment by cadesalaberry** [comment]
WOW great ! thanks @batjos !

**Pull request merged**
