### PR TITLE
update pkgcloud and use version 2.x

### PR DESCRIPTION
**Pull request by rachedanis**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by dhmlau** [comment]
@slnode test please

**Comment by rachedanis** [comment]
Hello @dhmlau @virkt25 @jannyHou @b-admike, can anyone perform the merge since all checks are OK :) ?

**Comment by dhmlau** [comment]
@rachedanis , thanks for your contribution.  Your PR has landed!

**Comment by dhmlau** [comment]
`loopback-component-storage@3.6.1` is released.

**Pull request merged**
