### PR TITLE
{download,upload}Stream: removed callback from doc

### PR DESCRIPTION
**Pull request by tkrugg**
### Description

downloadStream, uploadStream: removed callback from doc 

#### Related issues
- connect to #254 

### Checklist

- [ ] New tests added or existing tests modified to cover all changes (NA)
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by dhmlau** [comment]
@slnode test please

**Comment by virkt25** [comment]
Mergin as the failures are related to linting errors in code. I'll open a new PR to address those.

**Comment by virkt25** [comment]
@tkrugg Your PR has landed 🎉! Thanks for your contribution ❤️

**Pull request merged**
