### PR TITLE
Update factory.js

### LINKED ISSUE #123: How to upload a file?
How can I upload a file? I have the file in a JavaScript File()-Object. When I POST this it throws an error 500 unknow type `image/jpeg`.
When I wrap it like this `{ file: <File>, type: "image/jpeg" }` it doesn't respond.
How do I upload a file correctly?

One time I had an error where the file size was to big. Can I extend it?

### PR DESCRIPTION
**Pull request by juanvillegas**
Attempt to address https://github.com/strongloop/loopback-component-storage/issues/289. Looking forward to comments.

Note: I'm aware this change breaks most of the tests, and I'll continue looking into it to try to get a better understanding of what's going on. But, as requested in the original Issue where we discussed this, I'm pushing it so that someone in the team can take a look.

Thanks in advance.

Juan Villegas
Software Engineering @ smylen.com

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-component-storage) 👈

- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](https://loopback.io/doc/en/contrib/style-guide-es6.html)
- [ ] Commit messages are following our [guidelines](https://loopback.io/doc/en/contrib/git-commit-messages.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by juanvillegas** [comment]
Wondering if there is any progress on this one? Our team forked the library into a repository of our own with the changes suggested here, and we got rid of the errors mentioned in #289 . 
I'll try to take a look at the tests during the weekend.

**Comment by dhmlau** [comment]
@juanvillegas, yes, please add the tests to verify the changes. Thanks.
Also, could you please fix the commit linter error as well? 
```
**************************************************
**
**  Linting commit logs
**
**  1 problems found:
**    c4a5a93 - Update factory.js: line 3 longer than 72 characters.
**
**************************************************
```

**Comment by dhmlau** [comment]
@hacksparrow, could you please take a look? Thanks.

**Pull request closed without merging**
