### PR TITLE
Adding a setFilename method to customize the remote filename

### PR DESCRIPTION
**Pull request by neyric**
Sample usage : 

````js
var ds = loopback.createDataSource({
    connector: require('loopback-component-storage'),
    provider: 'amazon',
    keyId: '...',
    key: '....',

    // setFilename will be called multiple times for each "part" of the form upload
    setFilename: function (origFilename, req, res) {
        // optimisticly get the extension
        var parts = origFilename.split('.'),
            extension = parts[parts.length-1];

        // Using a local timestamp + user id in the filename (you might want to change this)
        var newFilename = (new Date()).getTime()+'_'+req.user.id+'.'+extension;
        return newFilename;
    }
});
var container = ds.createModel('container');
app.model(container);
````

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by seriousben** [comment]
I would like to merge this with #41 - so that we can support overriding the renamer per handler/endpoint.

**Comment by neyric** [comment]
Same as https://github.com/strongloop/loopback-component-storage/pull/41

**Comment by shSina** [comment]
the solution does not support dynamic names (ex. fetched from db callback), better to return a promise or handle it using callback.

**Pull request closed without merging**
