### PR TITLE
Added support for external providers as npm modules.

### PR DESCRIPTION
**Pull request by vergara**
@raymondfeng 
Here are again the changes that allow you to use your own implementations of storage providers. This time I signed the CLA.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by nickcmaynard** [comment]
+1
@vergara - I suspect this is blocked because you haven't signed the CLA :(

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by vergara** [comment]
@nickcmaynard 
I had signed the CLA long time ago. If I go now to

https://cla.strongloop.com/agreements/strongloop/loopback-component-storage

it shows me that I already signed the CLA.

Did I sign the right CLA?

**Comment by nickcmaynard** [comment]
@vergara Perhaps it's because the commit was authored by @cristobalvergara ?

**Comment by vergara** [comment]
@nickcmaynard 
You are right! I will take care of this as soon as I get a chance. Thank You!

**Comment by vergara** [comment]
Opened https://github.com/strongloop/loopback-component-storage/pull/122 with right github user as the author. Closing now.

**Comment by vergara** [comment]
@nickcmaynard 
I don't know why I cannot mention you in https://github.com/strongloop/loopback-component-storage/pull/122 but that PR is under the right user.

**Pull request closed without merging**
