### PR TITLE
Upgrade pkgcloud version

### PR DESCRIPTION
**Pull request by diegoazh**
### Description
This upgrade fix the bug in uploading files to google cloud storage.

#### Related issues
Upload method never calls the callback function: [#273](https://github.com/strongloop/loopback-component-storage/issues/273)

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@diegoazh, thanks for your contribution.  Your PR has landed! 🎉

**Comment by diegoazh** [comment]
When you think this change will be released?

**Comment by dhmlau** [comment]
@diegoazh, we're in the process of getting other community PRs to land before the release. 
See if we can do it by end of this week, if not, I can release it on Friday anyway. Thanks!

**Comment by dhmlau** [comment]
@diegoazh, thanks for taking up the 2 stale PRs. :)  
It probably needs to take some more time to get those to merge, so I made a new release of this module that contains the changes in this PR. Thanks!

**Comment by diegoazh** [comment]
Thank you @dhmlau

**Pull request merged**
