### PR TITLE
Added support for external providers as npm modules.

### PR DESCRIPTION
**Pull request by cristobalvergara**
@raymondfeng 
These changes allow you to use your own implementations of storage providers.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by raymondfeng** [comment]
@cristobalvergara Can you sign the CLA at https://cla.strongloop.com/agreements/strongloop/loopback-component-storage?

**Comment by cristobalvergara** [comment]
@raymondfeng I apologize for the delay. I am waiting for the green light from my employer to sign the agreement. I am expecting a response in the next two days.

**Comment by Traksewt** [comment]
We would like this fix too. Is there any plan to merge it in?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by raymondfeng** [comment]
Dup of https://github.com/strongloop/loopback-component-storage/pull/122

**Pull request closed without merging**
