### PR TITLE
Update validateName() to support file name with slash

### PR DESCRIPTION
**Pull request by FangFangHuo**
#### Related issues
#231 

### Checklist
- [ ] Allow upload files with slash in the name, such as '/namespace1/namespace2/filename'
- [ ] Create folder if it does not exist in file path '/namespace1/namespace2/filename'

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by dhmlau** [comment]
@FangFangHuo, thanks for your contribution.  Could you please sign the CLA https://cla.strongloop.com/agreements/strongloop/loopback-component-storage?  Thanks.

**Comment by FangFangHuo** [comment]
@dhmlau I have sign the CLA already, thanks.

**Comment by FangFangHuo** [comment]
@raymondfeng   Hi, raymon, I am from IBM and want to talk this PR with you, could you contact me with email or Slack? bjhffhuo@cn.ibm.com, thanks.

**Comment by raymondfeng** [comment]
@FangFangHuo Do you see overlapping between this and https://github.com/strongloop/loopback-component-storage/pull/217?

Can you add a test case?

With `/` support, we probably need to make sure `..` is not allowed to prevent file access beyond the root dir.

**Pull request closed without merging**
