### PR TITLE
Fix for issue #251

### PR DESCRIPTION
**Pull request by ketansp**
### Description
Fix for issue #251 

#### Related issues
connect to #251 

### Checklist
```
- [ ] a task list item
- [ ] list syntax required
- [ ] normal **formatting**, @mentions, #1234 refs
- [ ] incomplete
- [x] completed
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
```

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by jannyHou** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@jannyHou , it might just be linting errors? 
```
12:39:39 /home/jenkins/workspace/nb/loopback-component-storage~master/7a48ad0e/lib/providers/filesystem/index.js
12:39:39   33:1  error  Line 33 exceeds the maximum line length of 90  max-len
12:39:39 
12:39:39 /home/jenkins/workspace/nb/loopback-component-storage~master/7a48ad0e/lib/storage-handler.js
12:39:39    57:13  error  Unexpected newline before ')'  function-paren-newline
12:39:39    57:14  error  Expected a newline before ')'  function-paren-newline
12:39:39   110:13  error  Unexpected newline before ')'  function-paren-newline
12:39:39   110:14  error  Expected a newline before ')'  function-paren-newline
12:39:39   209:13  error  Unexpected newline before ')'  function-paren-newline
12:39:39   209:14  error  Expected a newline before ')'  function-paren-newline
12:39:39 
```

**Comment by agnes512** [comment]
@slnode test please

**Comment by diegoazh** [comment]
@jannyHou are you working on this changes?

**Comment by dhmlau** [comment]
superseded by PR #279

**Pull request closed without merging**
