### PR TITLE
Fix: Report 404 if file not found.

### PR DESCRIPTION
**Pull request by cadesalaberry**
Was incorrectly returning a `500` if it failed to find the file to download.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by richardpringle** [comment]
ok to test

**Comment by cadesalaberry** [comment]
Should be fixed by #174

**Pull request closed without merging**
