### PR TITLE
Fix issue for download files in subfolder

### PR DESCRIPTION
**Pull request by andrei0807**
After delete this code line, I can download file from subfolder in linux.

#### Related issues

- connect to <link_to_referenced_issue>

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by dhmlau** [comment]
@andrei0807 , thanks for your PR. Could you please sign the CLA? https://cla.strongloop.com/agreements/strongloop/loopback-component-storage

Also, there's a commit linter error. 
```
**************************************************
**
**  Linting commit logs
**
**  1 problems found:
**    2402269 - Fix issue for download files in subfolder: line 3 longer than 72 characters.
**
**************************************************
```

As a reference, here is the commit message guideline: https://loopback.io/doc/en/contrib/git-commit-messages.html.

**Comment by dhmlau** [comment]
@strongloop/sq-lb-apex @hacksparrow, could you please help to review this PR? Thanks.

**Comment by andrei0807** [comment]
@dhmlau 
I had signed the CLA.
Should I request again?

**Comment by dhmlau** [comment]
@andrei0807, the CLA is fine now.  Could you please fix the commit linter error too? Thanks. :)

**Comment by andrei0807** [comment]
@dhmlau 
ok

**Comment by andrei0807** [comment]
@dhmlau 
image
I did change only one line.
I don't know why the code has linter issue.
Please tell me how to fix the issue.
Thanks

**Comment by agnes512** [comment]
> I don't know why the code has linter issue.
> Please tell me how to fix the issue.

I think that's probably that your git commit message is too long.
try `git commit --amend` to make the commit message shorter and push it again :smile:

**Comment by andrei0807** [comment]
@agnes512 
ok

**Comment by andrei0807** [comment]
https://github.com/strongloop/loopback-component-storage/pull/278
I request pull again.

**Comment by dhmlau** [comment]
@andrei0807 , looks like you've created another pull request #278. so i'm going to close this PR.

In the future, you don't need to create a new PR.  You can follow this instruction to amend the commit message and push again. https://help.github.com/en/articles/changing-a-commit-message.  Hope it helps. Thanks.

**Comment by diegoazh** [comment]
@andrei0807 a new PR is not necessary if you push to the same branch with force after correcting your code this PR will be fixed.

1. `commit --amend`
2. Fix the commit
3. `git push <remote> <your-branch> --force`

I think you need close one of this PRs. I hope this helps you.
Regards.

**Pull request closed without merging**
