### PR TITLE
added file field name into getFilename function in storage-handler

### PR DESCRIPTION
**Pull request by hgouveia**
Appending the field name into the file object parameter on getFilename allow users to change the name of the files base of the field name, specially when the user is uploading multiple files and need to identify each one ex: original image and thumbnail in one post, and those use an special file naming convention

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by richardpringle** [comment]
ok to test

**Comment by richardpringle** [comment]
@hgouveia, did you run `npm test` before submitting the patch? You have some style issues....

**Comment by hgouveia** [comment]
@richardpringle I did,  and all test passed,  the issue was because the commit message was too long,

**Comment by richardpringle** [comment]
@slnode test please

Windows node 0.10 failed. re-running test to see if the issue persists

**Comment by hgouveia** [comment]
Hello, any updated about this? , thanks

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by richardpringle** [comment]
@loay, you'll need to re-verify and re-run the tests on this patch. It should be pretty easy to land if the tests pass (and I think it's a valuable patch).

**Pull request merged**
